export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_ERROR = 'LOGIN_REQUEST_ERROR';
export const LOGIN_RESTORE_SESSION_REQUEST = 'LOGIN_RESTORE_SESSION';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_ERROR = 'LOGOUT_REQUEST_ERROR';

export const TOPICS_GET_REQUEST = 'TOPICS_GET_REQUEST';
export const TOPICS_GET_REQUEST_SUCCESS = 'TOPICS_GET_REQUEST_SUCCESS';
export const TOPICS_GET_REQUEST_ERROR = 'TOPICS_GET_REQUEST_ERROR';

export const TOPICS_SUBMIT_REQUEST = 'TOPICS_SUBMIT_REQUEST';
export const TOPICS_SUBMIT_REQUEST_SUCCESS = 'TOPICS_SUBMIT_REQUEST_SUCCESS';

export const MEMBER_SUBMIT_REQUEST = 'MEMBER_SUBMIT_REQUEST';
export const MEMBER_SUBMIT_REQUEST_SUCCESS = 'MEMBER_SUBMIT_REQUEST_SUCCESS';
export const MEMBER_SUBMIT_REQUEST_ERROR = 'MEMBER_SUBMIT_REQUEST_ERROR';

export const MEMBER_LEAVE_REQUEST = 'MEMBER_LEAVE_REQUEST';
export const MEMBER_LEAVE_REQUEST_SUCCESS = 'MEMBER_LEAVE_REQUEST_SUCCESS';
export const MEMBER_LEAVE_REQUEST_ERROR = 'MEMBER_LEAVE_REQUEST_ERROR';
