export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const TOPICS_GET_REQUEST = 'TOPICS_GET_REQUEST';
export const TOPICS_GET_REQUEST_SUCCESS = 'TOPICS_GET_REQUEST_SUCCESS';
export const TOPICS_GET_REQUEST_ERROR = 'TOPICS_GET_REQUEST_ERROR';
